FROM mysql:latest


ENV MYSQL_ROOT_PASSWORD=root


ENV MYSQL_DATABASE=mysql_db


ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin

## docker run --name mysql_db -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d mysql
