FROM postgres:latest


ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=postgres_db
ENV POSTGRES_USER=admin
ENV POSTGRES_USER_PASSWORD=admin

## docker run --name postgres_db -e POSTGRES_PASSWORD=root -p 5432:5432 -d postgres

